services:
  - type: web
    name: content-sharing-service
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8001
      - key: MONGO_URI
        fromService:
          name: content-mongodb
          type: pserv
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: content-redis
          type: redis
          property: connectionString
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRY
        value: 1hr
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://your-frontend-url.com
    healthCheckPath: /api/v1/health
    autoDeploy: true

  - type: pserv
    name: content-mongodb
    env: docker
    region: oregon
    plan: free
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    dockerfilePath: ./docker/mongodb.Dockerfile

  - type: redis
    name: content-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction 