

services:
  auth-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
       # Server Configuration
      - PORT=8000
      - SERVER_URL=http://localhost:8000

      - CLIENT_URL=http://localhost:8000/api/auth/Home

# Database Configuration
      - MONGO_URI=mongodb+srv://synchubb:fnB1ovNY1aWN8lj1@cluster0.6su60.mongodb.net/authDb

# Session Configuration
      - SESSION_SECRET=your_session_secret

# OAuth Configuration
      - GOOGLE_CLIENT_ID=1075886016697-qs5svce9mkl01kt7ukv3g1ooq555fkn7.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GITHUB_CLIENT_ID=Ov23liylfwydkt30CJlW
      - GITHUB_CLIENT_SECRET=4cb2f8ac317b086531c1866148b4c6912fe1cfe4
      - ACCESS_TOKEN_EXPIRY=1hr
      - ACCESS_TOKEN_SECRET=divsync
      - EMAIL=synchubb2@gmail.com
      - PASSWORD=uyyc vjvd jnys xqra
      - REFRESH_TOKEN_EXPIRY=5d
      - REFRESH_TOKEN_SECRET=divsyncujjwal
      - SESSION_SECRET=your_secret_key

    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - auth-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-network
    environment:
      - MONGO_INITDB_DATABASE=auth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  auth-network:
    driver: bridge
    name: auth-network

volumes:
  mongodb_data:
    name: auth-mongodb-data 